name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    name: Auto Merge Dependabot PRs
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' && 
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false
    
    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            return pr;

      - name: Check if minor/patch dependency update
        id: check-update
        run: |
          PR_TITLE="${{ steps.pr.outputs.result.title }}"
          echo "PR Title: $PR_TITLE"
          
          if echo "$PR_TITLE" | grep -E "(patch|minor)"; then
            echo "auto-merge=true" >> $GITHUB_OUTPUT
            echo "This is a patch/minor update, will auto-merge"
          else
            echo "auto-merge=false" >> $GITHUB_OUTPUT
            echo "This is a major update, manual review required"
          fi

      - name: Enable auto-merge
        if: steps.check-update.outputs.auto-merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Auto-approving dependabot patch/minor update after CI passes ✅'
            });
            
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            });
